### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by krukru** [degordian/qa-fortress#1]
Hello @zunjooo !

This issue is a reminder for you to write a few short words about how to contribute to QA fortress and how to improve it and keep it up to date. Thanks!

**Comment by zunjooo** [comment]
Hi @krukru ,

I added contribution guidelines here -> [link](https://github.com/degordian/qa-fortress/blob/master/docs/CONTRIBUTING.md), along with Issue templates.

Also I updated readme description on project with more info.

Thanks for reminder! 

Cheers!
